# Generated by Django 2.2.13 on 2020-07-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('archivo', models.FileField(storage=djongo.storage.GridFSStorage(base_url='/home/manuel/Documents/Django_projects/Reactify/srcmyfiles/', collection='myfiles'), upload_to='archivos')),
                ('id_loc', models.IntegerField()),
                ('id_tipo_archivo', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
