# Generated by Django 2.2.13 on 2020-07-02 06:40

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(base_url='/home/manuel/Documents/Django_projects/Reactify/srcmyfiles/', collection='myfiles'), upload_to='archivos'),
        ),
    ]
