# Generated by Django 2.2.13 on 2020-06-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
